/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projet_gl;

/**
 *
 * @author HP
 */
public class DepartementInputPan extends javax.swing.JPanel {
private static DepartementInputPan f = null;
    /**
     * Creates new form DepartementInputPan
     */
    public static DepartementInputPan ouvrirFenetre() {
        if(f==null){
            f = new DepartementInputPan();
        }
        return f;
    }
    private DepartementInputPan() {
        initComponents();
    }
    public String getLibelle(){
        return nomTextField10.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomTextField10 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(237, 237, 237));

        nomTextField10.setBackground(new java.awt.Color(237, 237, 237));
        nomTextField10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Libellé", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Roboto", 0, 16), new java.awt.Color(51, 51, 51))); // NOI18N
        nomTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomTextField10ActionPerformed1(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(nomTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(nomTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomTextField10ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTextField10ActionPerformed1
        // TODO add your handling code here:
    }//GEN-LAST:event_nomTextField10ActionPerformed1


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField nomTextField10;
    // End of variables declaration//GEN-END:variables
}
