/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projet_gl;

import control.Avocat;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.DBConnection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class ResourcesHumains extends javax.swing.JFrame {
public static Color menuItemFocusColor = new Color(31, 120, 255);
public static Color menuItemColor = new Color(29, 57, 140);
public static Color menuItemSelectedColor = new Color(56, 54, 199);
    /**
     * Creates new form ResourcesHumains
     */
    public ResourcesHumains() {
        
        initComponents();tableAvocat.setModel(remplirTableau(tableAvocat, "avocat"));
    }
    public DefaultTableModel remplirTableau(JTable jTable1, String table) {
        
        DefaultTableModel tabMod= null;
        try{
        Connection connection = null;
        Class.forName("com.mysql.cj.jdbc.Driver");//instance dynamique du driver de sqlite
            String url = "jdbc:mysql://localhost:3306/firme_avocat";// emplacement de la BDD dans mon projet
            String user = "root";
            String password = "";
            connection = DriverManager.getConnection(url, user, password);
         Statement st = connection.createStatement();
         String req = "SELECT * FROM " + table;
         ResultSet result= st.executeQuery(req);
         tabMod = new DefaultTableModel();
            
            ResultSetMetaData resultMetaData = result.getMetaData();
            int nombreCol = resultMetaData.getColumnCount();//nombre de colones
            String[] nomCol = new String[nombreCol];
            for (int i = 0; i < nombreCol; i++) {
                nomCol[i] = resultMetaData.getColumnName(i+1);
                
            }
            tabMod.setColumnIdentifiers(nomCol);
            String nom,p,a;
            String[] row = new String[nombreCol];
            int i = 0;
            while(result.next()){
                for (int j = 0; j < nombreCol; j++) {
                   row[j] = result.getString(j+1); 
                }
                tabMod.addRow(row);
            }
            
            connection.close();
   
        }catch (ClassNotFoundException | SQLException e){
            e.printStackTrace();
            
        }
        
        
        return tabMod;
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuChoix = new javax.swing.JPanel();
        ajoutAvLabel = new javax.swing.JLabel();
        ajoutSecLabel = new javax.swing.JLabel();
        ajoutClLabel = new javax.swing.JLabel();
        ajoutDepLabel = new javax.swing.JLabel();
        fentresRH = new javax.swing.JPanel();
        barControl = new javax.swing.JPanel();
        bouttonRetour = new javax.swing.JButton();
        fenetreGestion = new javax.swing.JPanel();
        gestionAvocat = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        boutonAjoutAv = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        boutonAjoutAv1 = new javax.swing.JButton();
        boutonAjoutAv2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAvocat = new javax.swing.JTable();
        gestionDepartement = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        boutonAjoutDep = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        boutonSuppDep = new javax.swing.JButton();
        boutonModDep = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDepartements = new javax.swing.JTable();
        gestionSecretaire = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        boutonAjoutSecretaire = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        boutonSuppSecretaire = new javax.swing.JButton();
        boutonModSecretaire = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSecretaire = new javax.swing.JTable();
        gestionClient = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        boutonAjoutClient = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        boutonSuppClient = new javax.swing.JButton();
        boutonModClient = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableClient = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        menuChoix.setPreferredSize(new java.awt.Dimension(300, 419));
        menuChoix.setLayout(new java.awt.GridLayout(4, 1));

        ajoutAvLabel.setBackground(menuItemColor);
        ajoutAvLabel.setFont(new java.awt.Font("Roboto", 1, 17)); // NOI18N
        ajoutAvLabel.setForeground(new java.awt.Color(255, 255, 255));
        ajoutAvLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ajoutAvLabel.setText("Gestion des Avocats");
        ajoutAvLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ajoutAvLabel.setOpaque(true);
        ajoutAvLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutAvLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajoutAvLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajoutAvLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ajoutAvLabelMousePressed(evt);
            }
        });
        menuChoix.add(ajoutAvLabel);

        ajoutSecLabel.setBackground(menuItemColor);
        ajoutSecLabel.setFont(new java.awt.Font("Roboto", 1, 17)); // NOI18N
        ajoutSecLabel.setForeground(new java.awt.Color(255, 255, 255));
        ajoutSecLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ajoutSecLabel.setText("Gestion des Secretaires");
        ajoutSecLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ajoutSecLabel.setOpaque(true);
        ajoutSecLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutSecLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajoutSecLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajoutSecLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ajoutSecLabelMousePressed(evt);
            }
        });
        menuChoix.add(ajoutSecLabel);

        ajoutClLabel.setBackground(menuItemColor);
        ajoutClLabel.setFont(new java.awt.Font("Roboto", 1, 17)); // NOI18N
        ajoutClLabel.setForeground(new java.awt.Color(255, 255, 255));
        ajoutClLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ajoutClLabel.setText("Gestion des Clients");
        ajoutClLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ajoutClLabel.setOpaque(true);
        ajoutClLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutClLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajoutClLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajoutClLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ajoutClLabelMousePressed(evt);
            }
        });
        menuChoix.add(ajoutClLabel);

        ajoutDepLabel.setBackground(menuItemColor);
        ajoutDepLabel.setFont(new java.awt.Font("Roboto", 1, 17)); // NOI18N
        ajoutDepLabel.setForeground(new java.awt.Color(255, 255, 255));
        ajoutDepLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ajoutDepLabel.setText("Gestion des Departements");
        ajoutDepLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ajoutDepLabel.setOpaque(true);
        ajoutDepLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutDepLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ajoutDepLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ajoutDepLabelMouseExited(evt);
            }
        });
        menuChoix.add(ajoutDepLabel);

        jPanel1.add(menuChoix, java.awt.BorderLayout.LINE_START);

        fentresRH.setLayout(new java.awt.BorderLayout());

        barControl.setPreferredSize(new java.awt.Dimension(636, 80));

        bouttonRetour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        bouttonRetour.setToolTipText("retour à la page d'accueil");
        bouttonRetour.setBorderPainted(false);
        bouttonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barControlLayout = new javax.swing.GroupLayout(barControl);
        barControl.setLayout(barControlLayout);
        barControlLayout.setHorizontalGroup(
            barControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bouttonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(572, Short.MAX_VALUE))
        );
        barControlLayout.setVerticalGroup(
            barControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bouttonRetour)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fentresRH.add(barControl, java.awt.BorderLayout.PAGE_START);

        fenetreGestion.setLayout(new java.awt.CardLayout());

        gestionAvocat.setBackground(new java.awt.Color(255, 255, 255));
        gestionAvocat.setLayout(new java.awt.BorderLayout());

        boutonAjoutAv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boutonAjoutAv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        boutonAjoutAv.setText("Ajouter");
        boutonAjoutAv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boutonAjoutAv.setIconTextGap(8);
        boutonAjoutAv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjoutAvActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        boutonAjoutAv1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boutonAjoutAv1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        boutonAjoutAv1.setText("Supprimer");
        boutonAjoutAv1.setEnabled(false);
        boutonAjoutAv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjoutAv1ActionPerformed(evt);
            }
        });

        boutonAjoutAv2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boutonAjoutAv2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        boutonAjoutAv2.setText("Modifier");
        boutonAjoutAv2.setEnabled(false);
        boutonAjoutAv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjoutAv2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boutonAjoutAv1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boutonAjoutAv2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boutonAjoutAv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(boutonAjoutAv, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonAjoutAv2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonAjoutAv1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gestionAvocat.add(jPanel2, java.awt.BorderLayout.LINE_START);

        tableAvocat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableAvocat.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableAvocat);
        ListSelectionModel selectionModel1 = tableAvocat.getSelectionModel();
        selectionModel1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent  evt) {
                int rowsNum = tableAvocat.getSelectedRowCount();

                if (!evt.getValueIsAdjusting()) {
                    // If a row is selected, enable the button
                    if (tableAvocat.getSelectedRow() != -1) {
                        boutonAjoutAv1.setEnabled(true);
                        boutonAjoutAv2.setEnabled(true);
                    } else  {
                        boutonAjoutAv1.setEnabled(false);
                        boutonAjoutAv2.setEnabled(false);
                    }
                    if(rowsNum>=2) boutonAjoutAv2.setEnabled(false);
                }

            }
        });

        gestionAvocat.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        fenetreGestion.add(gestionAvocat, "card2");

        gestionDepartement.setBackground(new java.awt.Color(255, 255, 255));
        gestionDepartement.setLayout(new java.awt.BorderLayout());

        boutonAjoutDep.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boutonAjoutDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        boutonAjoutDep.setText("Ajouter");
        boutonAjoutDep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boutonAjoutDep.setIconTextGap(8);
        boutonAjoutDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjoutDepActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        boutonSuppDep.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boutonSuppDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        boutonSuppDep.setText("Supprimer");
        boutonSuppDep.setEnabled(false);
        boutonSuppDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSuppDepActionPerformed(evt);
            }
        });

        boutonModDep.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boutonModDep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        boutonModDep.setText("Modifier");
        boutonModDep.setEnabled(false);
        boutonModDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonModDepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boutonSuppDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boutonModDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boutonAjoutDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(boutonAjoutDep, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonModDep, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonSuppDep, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gestionDepartement.add(jPanel3, java.awt.BorderLayout.LINE_START);

        tableDepartements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableDepartements);
        ListSelectionModel selectionModel = tableDepartements.getSelectionModel();
        selectionModel.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent  evt) {
                int rowsNum = tableDepartements.getSelectedRowCount();

                if (!evt.getValueIsAdjusting()) {
                    // If a row is selected, enable the button
                    if (tableDepartements.getSelectedRow() != -1) {
                        boutonModDep.setEnabled(true);
                        boutonSuppDep.setEnabled(true);
                    } else  {
                        boutonModDep.setEnabled(false);
                        boutonSuppDep.setEnabled(false);
                    }
                    if(rowsNum>=2) boutonModDep.setEnabled(false);
                }

            }
        });

        gestionDepartement.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        fenetreGestion.add(gestionDepartement, "card5");

        gestionSecretaire.setBackground(new java.awt.Color(255, 255, 255));
        gestionSecretaire.setLayout(new java.awt.BorderLayout());

        boutonAjoutSecretaire.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boutonAjoutSecretaire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        boutonAjoutSecretaire.setText("Ajouter");
        boutonAjoutSecretaire.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boutonAjoutSecretaire.setIconTextGap(8);
        boutonAjoutSecretaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjoutSecretaireActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setText("Refresh");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        boutonSuppSecretaire.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boutonSuppSecretaire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        boutonSuppSecretaire.setText("Supprimer");
        boutonSuppSecretaire.setEnabled(false);
        boutonSuppSecretaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSuppSecretaireActionPerformed(evt);
            }
        });

        boutonModSecretaire.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boutonModSecretaire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        boutonModSecretaire.setText("Modifier");
        boutonModSecretaire.setEnabled(false);
        boutonModSecretaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonModSecretaireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boutonSuppSecretaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boutonModSecretaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boutonAjoutSecretaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(boutonAjoutSecretaire, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonModSecretaire, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonSuppSecretaire, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gestionSecretaire.add(jPanel4, java.awt.BorderLayout.LINE_START);

        tableSecretaire.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableSecretaire.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tableSecretaire);
        ListSelectionModel selectionModel2 = tableSecretaire.getSelectionModel();
        selectionModel2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent  evt) {
                int rowsNum = tableSecretaire.getSelectedRowCount();

                if (!evt.getValueIsAdjusting()) {
                    // If a row is selected, enable the button
                    if (tableSecretaire.getSelectedRow() != -1) {
                        boutonModSecretaire.setEnabled(true);
                        boutonSuppSecretaire.setEnabled(true);
                    } else  {
                        boutonModSecretaire.setEnabled(false);
                        boutonSuppSecretaire.setEnabled(false);
                    }
                    if(rowsNum>=2) boutonModSecretaire.setEnabled(false);
                }

            }
        });

        gestionSecretaire.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        fenetreGestion.add(gestionSecretaire, "card3");

        gestionClient.setBackground(new java.awt.Color(255, 255, 255));
        gestionClient.setLayout(new java.awt.BorderLayout());

        boutonAjoutClient.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boutonAjoutClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        boutonAjoutClient.setText("Ajouter");
        boutonAjoutClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boutonAjoutClient.setIconTextGap(8);
        boutonAjoutClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAjoutClientActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        boutonSuppClient.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boutonSuppClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        boutonSuppClient.setText("Supprimer");
        boutonSuppClient.setEnabled(false);
        boutonSuppClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSuppClientActionPerformed(evt);
            }
        });

        boutonModClient.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boutonModClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        boutonModClient.setText("Modifier");
        boutonModClient.setEnabled(false);
        boutonModClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonModClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boutonSuppClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boutonModClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boutonAjoutClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(boutonAjoutClient, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonModClient, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonSuppClient, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gestionClient.add(jPanel5, java.awt.BorderLayout.LINE_START);

        tableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableClient.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tableClient);
        ListSelectionModel selectionModel3 = tableClient.getSelectionModel();
        selectionModel3.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent  evt) {
                int rowsNum = tableClient.getSelectedRowCount();

                if (!evt.getValueIsAdjusting()) {
                    // If a row is selected, enable the button
                    if (tableClient.getSelectedRow() != -1) {
                        boutonModClient.setEnabled(true);
                        boutonSuppClient.setEnabled(true);
                    } else  {
                        boutonModClient.setEnabled(false);
                        boutonSuppClient.setEnabled(false);
                    }
                    if(rowsNum>=2) boutonModClient.setEnabled(false);
                }

            }
        });

        gestionClient.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        fenetreGestion.add(gestionClient, "card4");

        fentresRH.add(fenetreGestion, java.awt.BorderLayout.CENTER);

        jPanel1.add(fentresRH, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajoutAvLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutAvLabelMouseEntered
        // TODO add your handling code here:
        ajoutAvLabel.setBackground(menuItemFocusColor);
    }//GEN-LAST:event_ajoutAvLabelMouseEntered

    private void ajoutAvLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutAvLabelMouseExited
        ajoutAvLabel.setBackground(menuItemColor);
    }//GEN-LAST:event_ajoutAvLabelMouseExited

    private void ajoutAvLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutAvLabelMousePressed
        // TODO add your handling code here:
        ajoutAvLabel.setBackground(menuItemSelectedColor);
        

    }//GEN-LAST:event_ajoutAvLabelMousePressed

    private void ajoutSecLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutSecLabelMouseEntered
        // TODO add your handling code here:
        ajoutSecLabel.setBackground(menuItemFocusColor);
    }//GEN-LAST:event_ajoutSecLabelMouseEntered

    private void ajoutClLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutClLabelMouseExited
        // TODO add your handling code here:
        ajoutClLabel.setBackground(menuItemColor);
    }//GEN-LAST:event_ajoutClLabelMouseExited

    private void ajoutDepLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutDepLabelMouseEntered
        // TODO add your handling code here:
        ajoutDepLabel.setBackground(menuItemFocusColor);
    }//GEN-LAST:event_ajoutDepLabelMouseEntered

    private void ajoutClLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutClLabelMouseEntered
        // TODO add your handling code here:
        ajoutClLabel.setBackground(menuItemFocusColor);
    }//GEN-LAST:event_ajoutClLabelMouseEntered

    private void ajoutSecLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutSecLabelMouseExited
        // TODO add your handling code here:
        ajoutSecLabel.setBackground(menuItemColor);
    }//GEN-LAST:event_ajoutSecLabelMouseExited

    private void ajoutDepLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutDepLabelMouseExited
        // TODO add your handling code here:
        ajoutDepLabel.setBackground(menuItemColor);
    }//GEN-LAST:event_ajoutDepLabelMouseExited

    private void ajoutDepLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutDepLabelMouseClicked
        // TODO add your handling code here:
        tableDepartements.setModel(remplirTableau(tableDepartements,"departement" ));
        
        CardLayout card = (CardLayout)fenetreGestion.getLayout();
        card.show(fenetreGestion, "card5");
        
        
    }//GEN-LAST:event_ajoutDepLabelMouseClicked

    private void ajoutClLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutClLabelMousePressed
        // TODO add your handling code here:
        ajoutClLabel.setBackground(menuItemSelectedColor);
    }//GEN-LAST:event_ajoutClLabelMousePressed

    private void ajoutSecLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutSecLabelMousePressed
        // TODO add your handling code here:
        ajoutSecLabel.setBackground(menuItemSelectedColor);
    }//GEN-LAST:event_ajoutSecLabelMousePressed

    private void bouttonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonRetourActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        javax.swing.JFrame f = new Welcome();
        f.setBounds(this.getBounds());
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bouttonRetourActionPerformed

    private void ajoutAvLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutAvLabelMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)fenetreGestion.getLayout();
        card.show(fenetreGestion, "card2");
    }//GEN-LAST:event_ajoutAvLabelMouseClicked

    private void ajoutSecLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutSecLabelMouseClicked
        // TODO add your handling code here:
        tableSecretaire.setModel(remplirTableau(tableSecretaire, "secretaire"));
        CardLayout card = (CardLayout)fenetreGestion.getLayout();
        card.show(fenetreGestion, "card3");
    }//GEN-LAST:event_ajoutSecLabelMouseClicked

    private void ajoutClLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutClLabelMouseClicked
        // TODO add your handling code here:
        tableClient.setModel(remplirTableau(tableClient, "client"));
        CardLayout card = (CardLayout)fenetreGestion.getLayout();
        card.show(fenetreGestion, "card4");
    }//GEN-LAST:event_ajoutClLabelMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tableAvocat.setModel(remplirTableau(tableAvocat, "avocat"));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void boutonAjoutAvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjoutAvActionPerformed
        // TODO add your handling code here:
        javax.swing.JFrame f = AjoutSecreataire.ouvrirFenetreAjoutAvocat();
        f.setAlwaysOnTop(true);
        
        f.setVisible(true);
        f.setResizable(false);
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResourcesHumains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResourcesHumains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResourcesHumains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResourcesHumains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boutonAjoutAvActionPerformed

    private void boutonAjoutAv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjoutAv1ActionPerformed
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(rootPane, "voulez-vous vraiment supprimer cette avocat?", "confirmation de suppression", JOptionPane.YES_NO_OPTION);
        if(reponse == JOptionPane.YES_OPTION){
        int[] tuplesSelectione = tableAvocat.getSelectedRows();
        Connection connection = null;
       
            try{
        connection = DBConnection.etablirConnection();
        for(int i: tuplesSelectione){
            String deleteQuery = "DELETE FROM `avocat` WHERE idAvocat = ?";
            PreparedStatement preparedStatement = connection.prepareStatement(deleteQuery);
            int id = Integer.parseInt((String)tableAvocat.getValueAt(i, 0)); // Assuming ID is in the first column
            preparedStatement.setLong(1, id);
            preparedStatement.executeUpdate();
            
        }}catch(SQLException e){
            e.printStackTrace();
        }
            try {
                connection.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        
        jButton2ActionPerformed(evt);}
        
        
    }//GEN-LAST:event_boutonAjoutAv1ActionPerformed

    private void boutonAjoutAv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjoutAv2ActionPerformed
        // TODO add your handling code here:
        int i = tableAvocat.getSelectedRow();
        String id =(String)tableAvocat.getValueAt(i, 0);
        try{
        ResultSet res = Avocat.getAvocat(Integer.parseInt(id));
        ModAvocat f = ModAvocat.ouvrirFenetreAjoutAvocat();
            while(res.next()){
            f.setNom(res.getString("nom"));
            f.setPrenom(res.getString("prenom"));
            f.setAdresse(res.getString("adresse"));
            f.setSalaire(res.getString("salaire"));
            f.setNumeroPermis(res.getString("numeroPermis"));
            f.setNumeroIdNational(res.getString("numIdNationale"));
            f.setLieuNaissance(res.getString("lieuNaissance"));
            f.setAnneeNaissance(res.getString("anneeNaissance"));
            f.setJourNaissance(res.getString("jourNaissance"));
            f.setJourFinService(res.getString("jourFinService"));
            f.setAnneeFinService(res.getString("anneeFinService"));
            f.setJourRecrutement(res.getString("jourRecrutement"));
            f.setAnneeRecrutement(res.getString("anneeRecrutement"));
            f.setMoisRecrutement(res.getInt("moisRecrutement"));
            f.setMoisFinService(res.getInt("moisFinService"));
            f.setMoisNaissance(res.getInt("moisNaissance"));
            f.setDepartement(control.Departement.getLibelleDepartement(res.getInt("idDepartement")));
            }
            f.setVisible(true);
        }
        catch(NumberFormatException |SQLException e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_boutonAjoutAv2ActionPerformed

    private void boutonAjoutDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjoutDepActionPerformed
        // TODO add your handling code here:
        DepartementInputPan p = DepartementInputPan.ouvrirFenetre();
        int resultat = JOptionPane.showConfirmDialog(this, p, "Saisissez le nom du Département",
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (resultat == JOptionPane.OK_OPTION){
            String libelle = p.getLibelle();
            control.Departement d = new control.Departement(libelle);
            int message = control.Departement.AjouterDepartement(d);
            switch (message) {
                case (control.Constants.AJOUTE_AVEC_SUCCEE):
                    JOptionPane.showMessageDialog(this, "Ajoute avec succes", null, JOptionPane.INFORMATION_MESSAGE);
                    AjoutSecreataire.remplirComboBoxDept();
                    
                    break;
                case (control.Constants.PROBLEME_DE_CONNEXION_BDD):
                JOptionPane.showMessageDialog(this, "Probleme de connexion à la BDD", null, JOptionPane.ERROR_MESSAGE);
                break;
                case (control.Constants.ELEMENT_DEJA_DANS_BDD):
                JOptionPane.showMessageDialog(this, "Le département que vous essayez d'ajouter est déjà dans la base de données", null, JOptionPane.ERROR_MESSAGE);
                break;
                default:
                    throw new AssertionError();
            }
        }
        
        
    }//GEN-LAST:event_boutonAjoutDepActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        tableDepartements.setModel(remplirTableau(tableDepartements,"departement" ));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void boutonSuppDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSuppDepActionPerformed
        // TODO add your handling code here:
         int reponse = JOptionPane.showConfirmDialog(rootPane, "voulez-vous vraiment supprimer ce Département?", "confirmation de suppression", JOptionPane.YES_NO_OPTION);
        if(reponse == JOptionPane.YES_OPTION){
        int[] tuplesSelectione = tableDepartements.getSelectedRows();
        Connection connection = null;
       
            try{
        connection = DBConnection.etablirConnection();
        for(int i: tuplesSelectione){
            String deleteQuery = "DELETE FROM `departement` WHERE idDepartement = ?";
            PreparedStatement preparedStatement = connection.prepareStatement(deleteQuery);
            int id = Integer.parseInt((String)tableDepartements.getValueAt(i, 0)); // Assuming ID is in the first column
            preparedStatement.setInt(1, id);
            preparedStatement.executeUpdate();
            
        }}catch(SQLException e){
            e.printStackTrace();
        }
            try {
                connection.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        jButton3ActionPerformed(evt);}
        
        
    }//GEN-LAST:event_boutonSuppDepActionPerformed

    private void boutonModDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonModDepActionPerformed
        // TODO add your handling code here:
        int selectedRow =tableDepartements.getSelectedRow();
        
        String libelle = JOptionPane.showInputDialog(rootPane, "Insérer une nouvelle libelle");
        if(libelle!=null){
        int id = Integer.parseInt((String) tableDepartements.getValueAt(selectedRow, 0)) ;
        control.Departement.modifierDept(id, libelle);
        tableDepartements.setModel(remplirTableau(tableDepartements,"departement" ));}
        
        
        
    }//GEN-LAST:event_boutonModDepActionPerformed

    private void boutonAjoutSecretaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjoutSecretaireActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_boutonAjoutSecretaireActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        tableSecretaire.setModel(remplirTableau(tableSecretaire, "secretaire"));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void boutonSuppSecretaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSuppSecretaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonSuppSecretaireActionPerformed

    private void boutonModSecretaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonModSecretaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonModSecretaireActionPerformed

    private void boutonAjoutClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjoutClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonAjoutClientActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       tableClient.setModel(remplirTableau(tableClient, "client"));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void boutonSuppClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSuppClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonSuppClientActionPerformed

    private void boutonModClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonModClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonModClientActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResourcesHumains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResourcesHumains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResourcesHumains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResourcesHumains.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResourcesHumains().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ajoutAvLabel;
    private javax.swing.JLabel ajoutClLabel;
    private javax.swing.JLabel ajoutDepLabel;
    private javax.swing.JLabel ajoutSecLabel;
    private javax.swing.JPanel barControl;
    private javax.swing.JButton boutonAjoutAv;
    private javax.swing.JButton boutonAjoutAv1;
    private javax.swing.JButton boutonAjoutAv2;
    private javax.swing.JButton boutonAjoutClient;
    private javax.swing.JButton boutonAjoutDep;
    private javax.swing.JButton boutonAjoutSecretaire;
    private javax.swing.JButton boutonModClient;
    private javax.swing.JButton boutonModDep;
    private javax.swing.JButton boutonModSecretaire;
    private javax.swing.JButton boutonSuppClient;
    private javax.swing.JButton boutonSuppDep;
    private javax.swing.JButton boutonSuppSecretaire;
    private javax.swing.JButton bouttonRetour;
    private javax.swing.JPanel fenetreGestion;
    private javax.swing.JPanel fentresRH;
    private javax.swing.JPanel gestionAvocat;
    private javax.swing.JPanel gestionClient;
    private javax.swing.JPanel gestionDepartement;
    private javax.swing.JPanel gestionSecretaire;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel menuChoix;
    private javax.swing.JTable tableAvocat;
    private javax.swing.JTable tableClient;
    private javax.swing.JTable tableDepartements;
    private javax.swing.JTable tableSecretaire;
    // End of variables declaration//GEN-END:variables
}
